DROP TABLE IF EXISTS message_reactions;
DROP TABLE IF EXISTS message_files;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS chat_members;
DROP TABLE IF EXISTS reaction_types;
DROP TABLE IF EXISTS chats;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS chat_roles;