FROM golang:1.26.4-bookworm AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /app/cmd/vetmessager/exe /app/cmd/vetmessager

FROM alpine:3.14
WORKDIR /app
COPY --from=builder /app/cmd/vetmessager/exe /app
CMD ["/app/exe"]